### ISSUE TITLE
'Apple API Reference' shows 'Error. Please reinstall the API Ref docset'

### ISSUE THREAD

**Issue by waffleboot** [Kapeli/Dash-iOS#68]
macOS Dash 4.1.2
Dash iOS on iPad and from GitHub master branch

I transferred Apple API doc files from Dash macOS but when I try to open any documentation entry (class, protocol, etc) I see message 'Error. Please reinstall the Apple API Reference docset.' The reason in DHDocsetManager.m where 'DashDocSetIsGeneratedForiOSCompatibility' flag is checked.

Condition 
```
&& ![[[docset plist] objectForKey:@"DashDocSetIsGeneratedForiOSCompatibility"] boolValue]
```
returns false so I see error. I see valid info when I comment this line.

**Comment by MikePolinske** [comment]
I also noticed this on the version that is on the iOS App Store.

**Comment by Kapeli** [comment]
Thanks for catching this. The latest docsets shouldn't have that key when converted. I've fixed it.

Do this in Dash for macOS:
1. Check for updates in Preferences > Downloads
2. Go to Preferences > Docsets and convert the Apple API Reference docset for iOS
3. Transfer to iOS

**Comment by philosopherdog** [comment]
This is still happening for me even following the steps above. I'm using the current app store version. Is this working for everyone else?
